//"${COMPLETIONMODEL_SOURCES}",
// TODO: COMPLETIONMODEL_SOURCES

pub const tool_lib_cpp_files = &.{
    "ClangdMain.cpp",
    "Check.cpp",
};

pub const tool_cpp_files = &.{
    "ClangdToolMain.cpp",
};

pub const cpp_files = &.{
    "AST.cpp",
    "ASTSignals.cpp",
    "ClangdLSPServer.cpp",
    "ClangdServer.cpp",
    "CodeComplete.cpp",
    "CodeCompletionStrings.cpp",
    "CollectMacros.cpp",
    "CompileCommands.cpp",
    "Compiler.cpp",
    "Config.cpp",
    "ConfigCompile.cpp",
    "ConfigProvider.cpp",
    "ConfigYAML.cpp",
    "DecisionForest.cpp",
    "Diagnostics.cpp",
    "DraftStore.cpp",
    "DumpAST.cpp",
    "ExpectedTypes.cpp",
    "FeatureModule.cpp",
    "Feature.cpp",
    "FindSymbols.cpp",
    "FindTarget.cpp",
    "FileDistance.cpp",
    "Format.cpp",
    "FS.cpp",
    "FuzzyMatch.cpp",
    "GlobalCompilationDatabase.cpp",
    "Headers.cpp",
    "HeaderSourceSwitch.cpp",
    "Hover.cpp",
    "IncludeCleaner.cpp",
    "IncludeFixer.cpp",
    "InlayHints.cpp",
    "JSONTransport.cpp",
    "ModulesBuilder.cpp",
    "PathMapping.cpp",
    "Protocol.cpp",
    "Quality.cpp",
    "ParsedAST.cpp",
    "Preamble.cpp",
    "RIFF.cpp",
    "ScanningProjectModules.cpp",
    "Selection.cpp",
    "SemanticHighlighting.cpp",
    "SemanticSelection.cpp",
    "SourceCode.cpp",
    "SystemIncludeExtractor.cpp",
    "TidyProvider.cpp",
    "TUScheduler.cpp",
    "URI.cpp",
    "XRefs.cpp",

    "index/Background.cpp",
    "index/BackgroundIndexLoader.cpp",
    "index/BackgroundIndexStorage.cpp",
    "index/BackgroundQueue.cpp",
    "index/BackgroundRebuild.cpp",
    "index/CanonicalIncludes.cpp",
    "index/FileIndex.cpp",
    "index/Index.cpp",
    "index/IndexAction.cpp",
    "index/MemIndex.cpp",
    "index/Merge.cpp",
    "index/ProjectAware.cpp",
    "index/Ref.cpp",
    "index/Relation.cpp",
    "index/Serialization.cpp",
    "index/StdLib.cpp",
    "index/Symbol.cpp",
    "index/SymbolCollector.cpp",
    "index/SymbolID.cpp",
    "index/SymbolLocation.cpp",
    "index/SymbolOrigin.cpp",
    "index/YAMLSerialization.cpp",

    "index/dex/Dex.cpp",
    "index/dex/Iterator.cpp",
    "index/dex/PostingList.cpp",
    "index/dex/Trigram.cpp",

    "refactor/InsertionPoint.cpp",
    "refactor/Rename.cpp",
    "refactor/Tweak.cpp",
};

pub const tablegen_cpp_files = &.{
    "ASTTableGen.cpp",
    "ClangASTNodesEmitter.cpp",
    "ClangASTPropertiesEmitter.cpp",
    "ClangAttrEmitter.cpp",
    "ClangBuiltinsEmitter.cpp",
    "ClangCommentCommandInfoEmitter.cpp",
    "ClangCommentHTMLNamedCharacterReferenceEmitter.cpp",
    "ClangCommentHTMLTagsEmitter.cpp",
    "ClangDataCollectorsEmitter.cpp",
    "ClangDiagnosticsEmitter.cpp",
    "ClangOpcodesEmitter.cpp",
    "ClangOpenCLBuiltinEmitter.cpp",
    "ClangOptionDocEmitter.cpp",
    "ClangSACheckersEmitter.cpp",
    "ClangSyntaxEmitter.cpp",
    "ClangTypeNodesEmitter.cpp",
    "MveEmitter.cpp",
    "NeonEmitter.cpp",
    "RISCVVEmitter.cpp",
    "SveEmitter.cpp",
    "TableGen.cpp",
};

pub const demangle_cpp_files = &.{
    "Demangle.cpp",
    "ItaniumDemangle.cpp",
    "MicrosoftDemangle.cpp",
    "MicrosoftDemangleNodes.cpp",
    "RustDemangle.cpp",
    "DLangDemangle.cpp",
};
