pub const abseil_module = &.{
    "AbseilTidyModule.cpp",
    "CleanupCtadCheck.cpp",
    "DurationAdditionCheck.cpp",
    "DurationComparisonCheck.cpp",
    "DurationConversionCastCheck.cpp",
    "DurationDivisionCheck.cpp",
    "DurationFactoryFloatCheck.cpp",
    "DurationFactoryScaleCheck.cpp",
    "DurationRewriter.cpp",
    "DurationSubtractionCheck.cpp",
    "DurationUnnecessaryConversionCheck.cpp",
    "FasterStrsplitDelimiterCheck.cpp",
    "NoInternalDependenciesCheck.cpp",
    "NoNamespaceCheck.cpp",
    "RedundantStrcatCallsCheck.cpp",
    "StrCatAppendCheck.cpp",
    "StringFindStartswithCheck.cpp",
    "StringFindStrContainsCheck.cpp",
    "TimeComparisonCheck.cpp",
    "TimeSubtractionCheck.cpp",
    "UpgradeDurationConversionsCheck.cpp",
};

pub const altera_module = &.{
    "AlteraTidyModule.cpp",
    "IdDependentBackwardBranchCheck.cpp",
    "KernelNameRestrictionCheck.cpp",
    "SingleWorkItemBarrierCheck.cpp",
    "StructPackAlignCheck.cpp",
    "UnrollLoopsCheck.cpp",
};

pub const android_module = &.{
    "AndroidTidyModule.cpp",
    "CloexecAccept4Check.cpp",
    "CloexecAcceptCheck.cpp",
    "CloexecCheck.cpp",
    "CloexecCreatCheck.cpp",
    "CloexecDupCheck.cpp",
    "CloexecEpollCreate1Check.cpp",
    "CloexecEpollCreateCheck.cpp",
    "CloexecFopenCheck.cpp",
    "CloexecInotifyInit1Check.cpp",
    "CloexecInotifyInitCheck.cpp",
    "CloexecMemfdCreateCheck.cpp",
    "CloexecOpenCheck.cpp",
    "CloexecPipeCheck.cpp",
    "CloexecPipe2Check.cpp",
    "CloexecSocketCheck.cpp",
    "ComparisonInTempFailureRetryCheck.cpp",
};

pub const boost_module = &.{
    "BoostTidyModule.cpp",
    "UseRangesCheck.cpp",
    "UseToStringCheck.cpp",
};

pub const bugprone_module = &.{
    "ArgumentCommentCheck.cpp",
    "AssertSideEffectCheck.cpp",
    "AssignmentInIfConditionCheck.cpp",
    "BadSignalToKillThreadCheck.cpp",
    "BitwisePointerCastCheck.cpp",
    "BoolPointerImplicitConversionCheck.cpp",
    "BranchCloneCheck.cpp",
    "BugproneTidyModule.cpp",
    "CastingThroughVoidCheck.cpp",
    "ChainedComparisonCheck.cpp",
    "ComparePointerToMemberVirtualFunctionCheck.cpp",
    "CopyConstructorInitCheck.cpp",
    "CrtpConstructorAccessibilityCheck.cpp",
    "DanglingHandleCheck.cpp",
    "DynamicStaticInitializersCheck.cpp",
    "EasilySwappableParametersCheck.cpp",
    "EmptyCatchCheck.cpp",
    "ExceptionEscapeCheck.cpp",
    "FoldInitTypeCheck.cpp",
    "ForwardDeclarationNamespaceCheck.cpp",
    "ForwardingReferenceOverloadCheck.cpp",
    "ImplicitWideningOfMultiplicationResultCheck.cpp",
    "InaccurateEraseCheck.cpp",
    "IncorrectEnableIfCheck.cpp",
    "IncorrectEnableSharedFromThisCheck.cpp",
    "ReturnConstRefFromParameterCheck.cpp",
    "SuspiciousStringviewDataUsageCheck.cpp",
    "SwitchMissingDefaultCaseCheck.cpp",
    "IncDecInConditionsCheck.cpp",
    "IncorrectEnableIfCheck.cpp",
    "IncorrectRoundingsCheck.cpp",
    "InfiniteLoopCheck.cpp",
    "IntegerDivisionCheck.cpp",
    "LambdaFunctionNameCheck.cpp",
    "MacroParenthesesCheck.cpp",
    "MacroRepeatedSideEffectsCheck.cpp",
    "MisplacedOperatorInStrlenInAllocCheck.cpp",
    "MisplacedPointerArithmeticInAllocCheck.cpp",
    "MisplacedWideningCastCheck.cpp",
    "MoveForwardingReferenceCheck.cpp",
    "MultiLevelImplicitPointerConversionCheck.cpp",
    "MultipleNewInOneExpressionCheck.cpp",
    "MultipleStatementMacroCheck.cpp",
    "NarrowingConversionsCheck.cpp",
    "NoEscapeCheck.cpp",
    "NonZeroEnumToBoolConversionCheck.cpp",
    "NondeterministicPointerIterationOrderCheck.cpp",
    "NotNullTerminatedResultCheck.cpp",
    "OptionalValueConversionCheck.cpp",
    "ParentVirtualCallCheck.cpp",
    "PointerArithmeticOnPolymorphicObjectCheck.cpp",
    "PosixReturnCheck.cpp",
    "RedundantBranchConditionCheck.cpp",
    "ReservedIdentifierCheck.cpp",
    "ReturnConstRefFromParameterCheck.cpp",
    "SharedPtrArrayMismatchCheck.cpp",
    "SignalHandlerCheck.cpp",
    "SignedCharMisuseCheck.cpp",
    "SizeofContainerCheck.cpp",
    "SizeofExpressionCheck.cpp",
    "SmartPtrArrayMismatchCheck.cpp",
    "SpuriouslyWakeUpFunctionsCheck.cpp",
    "StandaloneEmptyCheck.cpp",
    "StringConstructorCheck.cpp",
    "StringIntegerAssignmentCheck.cpp",
    "StringLiteralWithEmbeddedNulCheck.cpp",
    "StringviewNullptrCheck.cpp",
    "SuspiciousEnumUsageCheck.cpp",
    "SuspiciousIncludeCheck.cpp",
    "SuspiciousMemoryComparisonCheck.cpp",
    "SuspiciousMemsetUsageCheck.cpp",
    "SuspiciousMissingCommaCheck.cpp",
    "SuspiciousReallocUsageCheck.cpp",
    "SuspiciousSemicolonCheck.cpp",
    "SuspiciousStringCompareCheck.cpp",
    "SuspiciousStringviewDataUsageCheck.cpp",
    "SwappedArgumentsCheck.cpp",
    "SwitchMissingDefaultCaseCheck.cpp",
    "TaggedUnionMemberCountCheck.cpp",
    "TerminatingContinueCheck.cpp",
    "ThrowKeywordMissingCheck.cpp",
    "TooSmallLoopVariableCheck.cpp",
    "UncheckedOptionalAccessCheck.cpp",
    "UndefinedMemoryManipulationCheck.cpp",
    "UndelegatedConstructorCheck.cpp",
    "UnhandledExceptionAtNewCheck.cpp",
    "UnhandledSelfAssignmentCheck.cpp",
    "UniquePtrArrayMismatchCheck.cpp",
    "UnsafeFunctionsCheck.cpp",
    "UnusedLocalNonTrivialVariableCheck.cpp",
    "UnusedRaiiCheck.cpp",
    "UnusedReturnValueCheck.cpp",
    "UseAfterMoveCheck.cpp",
    "VirtualNearMissCheck.cpp",
};

pub const cert_module = &.{
    "CERTTidyModule.cpp",
    "CommandProcessorCheck.cpp",
    "DefaultOperatorNewAlignmentCheck.cpp",
    "DontModifyStdNamespaceCheck.cpp",
    "FloatLoopCounter.cpp",
    "LimitedRandomnessCheck.cpp",
    "MutatingCopyCheck.cpp",
    "NonTrivialTypesLibcMemoryCallsCheck.cpp",
    "ProperlySeededRandomGeneratorCheck.cpp",
    "SetLongJmpCheck.cpp",
    "StaticObjectExceptionCheck.cpp",
    "StrToNumCheck.cpp",
    "ThrownExceptionTypeCheck.cpp",
    "VariadicFunctionDefCheck.cpp",
};

pub const concurrency = &.{
    "ConcurrencyTidyModule.cpp",
    "MtUnsafeCheck.cpp",
    "ThreadCanceltypeAsynchronousCheck.cpp",
};

pub const cppcoreguidelines_module = &.{
    "AvoidCapturingLambdaCoroutinesCheck.cpp",
    "AvoidConstOrRefDataMembersCheck.cpp",
    "AvoidDoWhileCheck.cpp",
    "AvoidGotoCheck.cpp",
    "AvoidNonConstGlobalVariablesCheck.cpp",
    "AvoidReferenceCoroutineParametersCheck.cpp",
    "CppCoreGuidelinesTidyModule.cpp",
    "InitVariablesCheck.cpp",
    "InterfacesGlobalInitCheck.cpp",
    "MacroUsageCheck.cpp",
    "MisleadingCaptureDefaultByValueCheck.cpp",
    "MissingStdForwardCheck.cpp",
    "NoMallocCheck.cpp",
    "NoSuspendWithLockCheck.cpp",
    "OwningMemoryCheck.cpp",
    "PreferMemberInitializerCheck.cpp",
    "ProBoundsArrayToPointerDecayCheck.cpp",
    "ProBoundsConstantArrayIndexCheck.cpp",
    "ProBoundsPointerArithmeticCheck.cpp",
    "ProTypeConstCastCheck.cpp",
    "ProTypeCstyleCastCheck.cpp",
    "ProTypeMemberInitCheck.cpp",
    "ProTypeReinterpretCastCheck.cpp",
    "ProTypeStaticCastDowncastCheck.cpp",
    "ProTypeUnionAccessCheck.cpp",
    "ProTypeVarargCheck.cpp",
    "RvalueReferenceParamNotMovedCheck.cpp",
    "SlicingCheck.cpp",
    "SpecialMemberFunctionsCheck.cpp",
    "VirtualClassDestructorCheck.cpp",
};

pub const darwin_modules = &.{
    "AvoidSpinlockCheck.cpp",
    "DarwinTidyModule.cpp",
    "DispatchOnceNonstaticCheck.cpp",
};

pub const fuchsia_module = &.{
    "DefaultArgumentsCallsCheck.cpp",
    "DefaultArgumentsDeclarationsCheck.cpp",
    "FuchsiaTidyModule.cpp",
    "MultipleInheritanceCheck.cpp",
    "OverloadedOperatorCheck.cpp",
    "StaticallyConstructedObjectsCheck.cpp",
    "TrailingReturnCheck.cpp",
    "VirtualInheritanceCheck.cpp",
};

pub const google_module = &.{
    "AvoidCStyleCastsCheck.cpp",
    "AvoidNSObjectNewCheck.cpp",
    "AvoidThrowingObjCExceptionCheck.cpp",
    "AvoidUnderscoreInGoogletestNameCheck.cpp",
    "DefaultArgumentsCheck.cpp",
    "ExplicitConstructorCheck.cpp",
    "ExplicitMakePairCheck.cpp",
    "FunctionNamingCheck.cpp",
    "GlobalNamesInHeadersCheck.cpp",
    "GlobalVariableDeclarationCheck.cpp",
    "GoogleTidyModule.cpp",
    "IntegerTypesCheck.cpp",
    "OverloadedUnaryAndCheck.cpp",
    "TodoCommentCheck.cpp",
    "UnnamedNamespaceInHeaderCheck.cpp",
    "UpgradeGoogletestCaseCheck.cpp",
    "UsingNamespaceDirectiveCheck.cpp",
};

pub const hicpp_module = &.{
    "ExceptionBaseclassCheck.cpp",
    "HICPPTidyModule.cpp",
    "IgnoredRemoveResultCheck.cpp",
    "MultiwayPathsCoveredCheck.cpp",
    "NoAssemblerCheck.cpp",
    "SignedBitwiseCheck.cpp",
};

pub const linuxkernel_module = &.{
    "LinuxKernelTidyModule.cpp",
    "MustCheckErrsCheck.cpp",
};

pub const llvm_module = &.{
    "HeaderGuardCheck.cpp",
    "IncludeOrderCheck.cpp",
    "LLVMTidyModule.cpp",
    "PreferIsaOrDynCastInConditionalsCheck.cpp",
    "PreferRegisterOverUnsignedCheck.cpp",
    "TwineLocalCheck.cpp",
};

pub const llvmlibc_module = &.{
    "CalleeNamespaceCheck.cpp",
    "ImplementationInNamespaceCheck.cpp",
    "InlineFunctionDeclCheck.cpp",
    "LLVMLibcTidyModule.cpp",
    "RestrictSystemLibcHeadersCheck.cpp",
};

pub const misc_module = &.{
    "ConstCorrectnessCheck.cpp",
    "CoroutineHostileRAIICheck.cpp",
    "DefinitionsInHeadersCheck.cpp",
    "ConfusableIdentifierCheck.cpp",
    "HeaderIncludeCycleCheck.cpp",
    "IncludeCleanerCheck.cpp",
    "MiscTidyModule.cpp",
    "MisleadingBidirectional.cpp",
    "MisleadingIdentifier.cpp",
    "MisplacedConstCheck.cpp",
    "NewDeleteOverloadsCheck.cpp",
    "NoRecursionCheck.cpp",
    "NonCopyableObjects.cpp",
    "NonPrivateMemberVariablesInClassesCheck.cpp",
    "RedundantExpressionCheck.cpp",
    "StaticAssertCheck.cpp",
    "ThrowByValueCatchByReferenceCheck.cpp",
    "UnconventionalAssignOperatorCheck.cpp",
    "UniqueptrResetReleaseCheck.cpp",
    "UnusedAliasDeclsCheck.cpp",
    "UnusedParametersCheck.cpp",
    "UnusedUsingDeclsCheck.cpp",
    "UseAnonymousNamespaceCheck.cpp",
    "UseInternalLinkageCheck.cpp",
};

pub const mpi_module = &.{
    "BufferDerefCheck.cpp",
    "MPITidyModule.cpp",
    "TypeMismatchCheck.cpp",
};

pub const objc_module = &.{
    "AssertEquals.cpp",
    "AvoidNSErrorInitCheck.cpp",
    "DeallocInCategoryCheck.cpp",
    "ForbiddenSubclassingCheck.cpp",
    "MissingHashCheck.cpp",
    "NSInvocationArgumentLifetimeCheck.cpp",
    "NSDateFormatterCheck.cpp",
    "ObjCTidyModule.cpp",
    "PropertyDeclarationCheck.cpp",
    "SuperSelfCheck.cpp",
};

pub const openmp_module = &.{
    "ExceptionEscapeCheck.cpp",
    "OpenMPTidyModule.cpp",
    "UseDefaultNoneCheck.cpp",
};

pub const performance_module = &.{
    "AvoidEndlCheck.cpp",
    "EnumSizeCheck.cpp",
    "FasterStringFindCheck.cpp",
    "ForRangeCopyCheck.cpp",
    "ImplicitConversionInLoopCheck.cpp",
    "InefficientAlgorithmCheck.cpp",
    "InefficientStringConcatenationCheck.cpp",
    "InefficientVectorOperationCheck.cpp",
    "MoveConstArgCheck.cpp",
    "MoveConstructorInitCheck.cpp",
    "NoAutomaticMoveCheck.cpp",
    "NoIntToPtrCheck.cpp",
    "NoexceptDestructorCheck.cpp",
    "NoexceptFunctionBaseCheck.cpp",
    "NoexceptMoveConstructorCheck.cpp",
    "NoexceptSwapCheck.cpp",
    "PerformanceTidyModule.cpp",
    "TriviallyDestructibleCheck.cpp",
    "TypePromotionInMathFnCheck.cpp",
    "UnnecessaryCopyInitialization.cpp",
    "UnnecessaryValueParamCheck.cpp",
};

pub const plugin_module = &.{
    "ClangTidyPlugin.cpp",
};

pub const portability = &.{
    "PortabilityTidyModule.cpp",
    "RestrictSystemIncludesCheck.cpp",
    "SIMDIntrinsicsCheck.cpp",
    "StdAllocatorConstCheck.cpp",
    "TemplateVirtualMemberFunctionCheck.cpp",
};

pub const readability = &.{
    "AvoidConstParamsInDecls.cpp",
    "AvoidNestedConditionalOperatorCheck.cpp",
    "AvoidReturnWithVoidValueCheck.cpp",
    "AvoidUnconditionalPreprocessorIfCheck.cpp",
    "BracesAroundStatementsCheck.cpp",
    "ConstReturnTypeCheck.cpp",
    "ContainerContainsCheck.cpp",
    "ContainerDataPointerCheck.cpp",
    "ContainerSizeEmptyCheck.cpp",
    "ConvertMemberFunctionsToStatic.cpp",
    "DeleteNullPointerCheck.cpp",
    "DuplicateIncludeCheck.cpp",
    "ElseAfterReturnCheck.cpp",
    "EnumInitialValueCheck.cpp",
    "FunctionCognitiveComplexityCheck.cpp",
    "FunctionSizeCheck.cpp",
    "IdentifierLengthCheck.cpp",
    "IdentifierNamingCheck.cpp",
    "ImplicitBoolConversionCheck.cpp",
    "RedundantInlineSpecifierCheck.cpp",
    "InconsistentDeclarationParameterNameCheck.cpp",
    "IsolateDeclarationCheck.cpp",
    "MagicNumbersCheck.cpp",
    "MakeMemberFunctionConstCheck.cpp",
    "MathMissingParenthesesCheck.cpp",
    "MisleadingIndentationCheck.cpp",
    "MisplacedArrayIndexCheck.cpp",
    "NamedParameterCheck.cpp",
    "NamespaceCommentCheck.cpp",
    "NonConstParameterCheck.cpp",
    "OperatorsRepresentationCheck.cpp",
    "QualifiedAutoCheck.cpp",
    "ReadabilityTidyModule.cpp",
    "RedundantAccessSpecifiersCheck.cpp",
    "RedundantCastingCheck.cpp",
    "RedundantControlFlowCheck.cpp",
    "RedundantDeclarationCheck.cpp",
    "RedundantFunctionPtrDereferenceCheck.cpp",
    "RedundantMemberInitCheck.cpp",
    "RedundantPreprocessorCheck.cpp",
    "RedundantSmartptrGetCheck.cpp",
    "RedundantStringCStrCheck.cpp",
    "RedundantStringInitCheck.cpp",
    "ReferenceToConstructedTemporaryCheck.cpp",
    "SimplifyBooleanExprCheck.cpp",
    "SimplifySubscriptExprCheck.cpp",
    "StaticAccessedThroughInstanceCheck.cpp",
    "StaticDefinitionInAnonymousNamespaceCheck.cpp",
    "StringCompareCheck.cpp",
    "SuspiciousCallArgumentCheck.cpp",
    "UniqueptrDeleteReleaseCheck.cpp",
    "UppercaseLiteralSuffixCheck.cpp",
    "UseAnyOfAllOfCheck.cpp",
    "UseStdMinMaxCheck.cpp",
};

pub const tool_module = &.{
    "ClangTidyMain.cpp",
};

pub const utils_module = &.{
    "Aliasing.cpp",
    "ASTUtils.cpp",
    "BracesAroundStatement.cpp",
    "DeclRefExprUtils.cpp",
    "DesignatedInitializers.cpp",
    "ExceptionAnalyzer.cpp",
    "ExceptionSpecAnalyzer.cpp",
    "ExprSequence.cpp",
    "FileExtensionsUtils.cpp",
    "FormatStringConverter.cpp",
    "FixItHintUtils.cpp",
    "HeaderGuard.cpp",
    "IncludeInserter.cpp",
    "IncludeSorter.cpp",
    "LexerUtils.cpp",
    "Matchers.cpp",
    "NamespaceAliaser.cpp",
    "OptionsUtils.cpp",
    "RenamerClangTidyCheck.cpp",
    "TransformerClangTidyCheck.cpp",
    "TypeTraits.cpp",
    "UseRangesCheck.cpp",
    "UsingInserter.cpp",
};

pub const zircon_module = &.{
    "TemporaryObjectsCheck.cpp",
    "ZirconTidyModule.cpp",
};
