const std = @import("std");

const Build = @import("build.zig");
const Context = Build.Context;
const sources = @import("clangd_sources.zig");

/// Fills out all the fields in Context.targets that start with clang_*
/// Called from root build.zig
pub fn build(ctx: *Context) void {
    ctx.targets.clang_basic_version_config_header = ctx.b.addConfigHeader(
        ctx.paths.clang.include.clang.basic.clang_basic_version_config_header.makeOptions(),
        .{
            .CLANG_VERSION = Build.version_string,
            .CLANG_VERSION_MAJOR = @as(i64, Build.version.major),
            .CLANG_VERSION_MINOR = @as(i64, Build.version.minor),
            .CLANG_VERSION_PATCHLEVEL = @as(i64, Build.version.patch),
            // from clang/CMakeLists.txt
            .MAX_CLANG_ABI_COMPAT_VERSION = @as(i64, Build.version.major),
        },
    );

    // NOTE: this is normally dynamically generated by the script
    // llvm/cmake/modules/GenerateVersionFromVCS.cmake and called from
    // clang/lib/Basic/CMakeLists.txt
    // but I do not care right now
    const vcs_version_inc = ctx.b.addWriteFile("VCSVersion.inc",
        \\#undef CLANG_REVISION
        \\#undef CLANG_REPOSITORY
        \\#undef LLVM_REVISION
        \\#undef LLVM_REPOSITORY
    );
    ctx.targets.clang_version_inc = vcs_version_inc.getDirectory();

    if (!ctx.opts.clang_enable_static_analyzer and ctx.opts.clang_enable_arcmt) {
        @panic("Cannot disable static analyzer while enabling ARCMT or Z3");
    }

    ctx.targets.clang_config_config_header = ctx.b.addConfigHeader(
        ctx.paths.clang.include.clang.config.config_config_header.makeOptions(),
        .{
            .BUG_REPORT_URL = Build.bug_report_url,
            .CLANG_DEFAULT_PIE_ON_LINUX = ctx.opts.clang_default_pie_on_linux,
            .CLANG_DEFAULT_LINKER = ctx.opts.clang_default_linker,
            .CLANG_DEFAULT_CXX_STDLIB = ctx.opts.clang_default_cxx_stdlib,
            .CLANG_DEFAULT_RTLIB = ctx.opts.clang_default_rtlib,
            .CLANG_DEFAULT_UNWINDLIB = ctx.opts.clang_default_unwindlib,
            .CLANG_DEFAULT_OBJCOPY = ctx.opts.clang_default_objcopy,
            .CLANG_DEFAULT_OPENMP_RUNTIME = ctx.opts.clang_default_openmp_runtime,
            .CLANG_SYSTEMZ_DEFAULT_ARCH = ctx.opts.clang_systemz_default_arch,
            .CLANG_INSTALL_LIBDIR_BASENAME = ctx.b.fmt("lib{s}", .{if (ctx.target.is_64_bit) "64" else ""}),
            .CLANG_RESOURCE_DIR = ctx.opts.clang_resource_dir,
            .C_INCLUDE_DIRS = ctx.opts.clang_c_include_dirs,
            .CLANG_CONFIG_FILE_SYSTEM_DIR = "", // TODO: how are these two dirs determined in original cmake?
            .CLANG_CONFIG_FILE_USER_DIR = "",
            .DEFAULT_SYSROOT = ctx.opts.default_sysroot,
            .GCC_INSTALL_PREFIX = ctx.opts.gcc_install_prefix,
            .CLANG_HAVE_LIBXML = ctx.opts.clang_enable_libxml2,
            .CLANG_HAVE_RLIMITS = Context.targetHasHeader(ctx.module_opts.target.?.result, .RLIMITS_H),
            .CLANG_HAVE_DLFCN_H = Context.targetHasHeader(ctx.module_opts.target.?.result, .DLFCN_H),
            .CLANG_HAVE_DLADDR = Context.targetHasSymbol(ctx.module_opts.target.?.result, .DLADDR),
            .HOST_LINK_VERSION = @as(i64, @intCast(ctx.opts.host_link_version)),
            .ENABLE_LINKER_BUILD_ID = ctx.opts.enable_linker_build_id,
            .ENABLE_X86_RELAX_RELOCATIONS = ctx.opts.enable_x86_relax_relocations,
            .PPC_LINUX_DEFAULT_IEEELONGDOUBLE = ctx.opts.ppc_linux_default_ieeelongdouble,
            .CLANG_ENABLE_ARCMT = ctx.opts.clang_enable_arcmt,
            .CLANG_ENABLE_OBJC_REWRITER = ctx.opts.clang_enable_arcmt,
            .CLANG_ENABLE_STATIC_ANALYZER = ctx.opts.clang_enable_static_analyzer,
            .CLANG_SPAWN_CC1 = ctx.opts.clang_spawn_cc1,
            .CLANG_ENABLE_CIR = ctx.opts.clang_enable_cir,
        },
    );

    ctx.targets.clang_host_component_support_lib = ctx.addClangLibrary(.{
        .name = "clangSupport",
        .root_module = ctx.makeHostModule(),
    });
    ctx.targets.clang_host_component_support_lib.?.addCSourceFiles(.{
        .root = ctx.paths.clang.lib.support.path,
        .files = sources.clang_support_lib_cpp_files,
        .flags = ctx.dupeGlobalFlags(),
        .language = .cpp,
    });
    // clang support also has llvm support and tablegen lib
    ctx.targets.clang_host_component_support_lib.?.linkLibrary(ctx.targets.llvm_host_component_tablegen_lib.?);

    ctx.targets.clang_host_component_tblgen_exe = ctx.addClangExecutable(.{
        .name = "clang-tblgen",
        .root_module = ctx.makeHostModule(),
    });
    ctx.targets.clang_host_component_tblgen_exe.?.addCSourceFiles(.{
        .files = sources.clang_tablegen_cpp_files,
        .root = ctx.paths.clang.utils.tablegen.path,
        .flags = ctx.dupeGlobalFlags(),
        .language = .cpp,
    });
    ctx.targets.clang_host_component_tblgen_exe.?.linkLibrary(ctx.targets.clang_host_component_support_lib.?);

    const writefile_step = ctx.b.addWriteFiles();

    // generate all the needed .inc files and copy them into the subdir
    for (ctx.clang_tablegen_files) |desc| {
        ctx.addTablegenOutputFileToWriteFileStep(writefile_step, ctx.targets.clang_host_component_tblgen_exe.?, desc);
    }
    ctx.targets.clang_tablegenerated_incs = writefile_step.getDirectory();

    {
        ctx.targets.clang_basic_lib = ctx.addClangLibrary(.{
            .name = "clangBasic",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_basic_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.basic.path,
            .files = sources.clang_basic_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_basic_lib.?.addIncludePath(ctx.paths.clang.lib.basic.path);
        ctx.targets.clang_basic_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_basic_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
    }

    {
        ctx.targets.clang_lex_lib = ctx.addClangLibrary(.{
            .name = "clangLex",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_lex_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.lex.path,
            .files = sources.clang_lex_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_lex_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_lex_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_lex_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
    }

    {
        ctx.targets.clang_ast_lib = ctx.addClangLibrary(.{
            .name = "clangAST",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_ast_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.ast.path,
            .files = sources.clang_ast_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_ast_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_ast_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_ast_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
        ctx.targets.clang_ast_lib.?.linkLibrary(ctx.targets.clang_lex_lib.?);
    }

    {
        ctx.targets.clang_ast_matchers_lib = ctx.addClangLibrary(.{
            .name = "clangASTMatchers",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_ast_matchers_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.ast_matchers.path,
            .files = sources.clang_ast_matchers_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_ast_matchers_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_ast_matchers_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_ast_matchers_lib.?.linkLibrary(ctx.targets.clang_ast_lib.?);
        ctx.targets.clang_ast_matchers_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
        ctx.targets.clang_ast_matchers_lib.?.linkLibrary(ctx.targets.clang_lex_lib.?);
    }

    {
        ctx.targets.clang_driver_lib = ctx.addClangLibrary(.{
            .name = "clangDriver",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_driver_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.driver.path,
            .files = sources.clang_driver_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_driver_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_driver_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_driver_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
    }

    {
        ctx.targets.clang_rewrite_lib = ctx.addClangLibrary(.{
            .name = "clangRewrite",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_rewrite_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.rewrite.path,
            .files = sources.clang_rewrite_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_rewrite_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_rewrite_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_rewrite_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
        ctx.targets.clang_rewrite_lib.?.linkLibrary(ctx.targets.clang_lex_lib.?);
    }

    {
        ctx.targets.clang_tooling_core_lib = ctx.addClangLibrary(.{
            .name = "clangToolingCore",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_tooling_core_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.tooling.core.path,
            .files = sources.clang_tooling_core_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_tooling_core_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_tooling_core_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_tooling_core_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
        ctx.targets.clang_tooling_core_lib.?.linkLibrary(ctx.targets.clang_lex_lib.?);
        ctx.targets.clang_tooling_core_lib.?.linkLibrary(ctx.targets.clang_rewrite_lib.?);
    }

    {
        ctx.targets.clang_tooling_inclusions_lib = ctx.addClangLibrary(.{
            .name = "clangToolingInclusions",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_tooling_inclusions_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.tooling.inclusions.path,
            .files = sources.clang_tooling_inclusions_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_tooling_inclusions_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_tooling_inclusions_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_tooling_inclusions_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
        ctx.targets.clang_tooling_inclusions_lib.?.linkLibrary(ctx.targets.clang_lex_lib.?);
        ctx.targets.clang_tooling_inclusions_lib.?.linkLibrary(ctx.targets.clang_tooling_core_lib.?);
    }

    {
        ctx.targets.clang_format_lib = ctx.addClangLibrary(.{
            .name = "clangFormat",
            .root_module = ctx.makeModule(),
        });
        ctx.targets.clang_format_lib.?.addCSourceFiles(.{
            .root = ctx.paths.clang.lib.format.path,
            .files = sources.clang_format_lib_cpp_files,
            .flags = ctx.dupeGlobalFlags(),
            .language = .cpp,
        });
        ctx.targets.clang_format_lib.?.addIncludePath(ctx.targets.clang_tablegenerated_incs.?);
        ctx.targets.clang_format_lib.?.addIncludePath(ctx.targets.llvm_tablegenerated_incs.?);
        ctx.targets.clang_format_lib.?.linkLibrary(ctx.targets.clang_basic_lib.?);
        ctx.targets.clang_format_lib.?.linkLibrary(ctx.targets.clang_lex_lib.?);
        ctx.targets.clang_format_lib.?.linkLibrary(ctx.targets.clang_tooling_core_lib.?);
        ctx.targets.clang_format_lib.?.linkLibrary(ctx.targets.clang_tooling_inclusions_lib.?);
    }
}
