//"${COMPLETIONMODEL_SOURCES}",
// TODO: COMPLETIONMODEL_SOURCES

pub const tool_lib_cpp_files = &.{
    "ClangdMain.cpp",
    "Check.cpp",
};

pub const tool_cpp_files = &.{
    "ClangdToolMain.cpp",
};

pub const cpp_files = &.{
    "AST.cpp",
    "ASTSignals.cpp",
    "ClangdLSPServer.cpp",
    "ClangdServer.cpp",
    "CodeComplete.cpp",
    "CodeCompletionStrings.cpp",
    "CollectMacros.cpp",
    "CompileCommands.cpp",
    "Compiler.cpp",
    "Config.cpp",
    "ConfigCompile.cpp",
    "ConfigProvider.cpp",
    "ConfigYAML.cpp",
    "DecisionForest.cpp",
    "Diagnostics.cpp",
    "DraftStore.cpp",
    "DumpAST.cpp",
    "ExpectedTypes.cpp",
    "FeatureModule.cpp",
    "Feature.cpp",
    "FindSymbols.cpp",
    "FindTarget.cpp",
    "FileDistance.cpp",
    "Format.cpp",
    "FS.cpp",
    "FuzzyMatch.cpp",
    "GlobalCompilationDatabase.cpp",
    "Headers.cpp",
    "HeaderSourceSwitch.cpp",
    "Hover.cpp",
    "IncludeCleaner.cpp",
    "IncludeFixer.cpp",
    "InlayHints.cpp",
    "JSONTransport.cpp",
    "ModulesBuilder.cpp",
    "PathMapping.cpp",
    "Protocol.cpp",
    "Quality.cpp",
    "ParsedAST.cpp",
    "Preamble.cpp",
    "RIFF.cpp",
    "ScanningProjectModules.cpp",
    "Selection.cpp",
    "SemanticHighlighting.cpp",
    "SemanticSelection.cpp",
    "SourceCode.cpp",
    "SystemIncludeExtractor.cpp",
    "TidyProvider.cpp",
    "TUScheduler.cpp",
    "URI.cpp",
    "XRefs.cpp",

    "index/Background.cpp",
    "index/BackgroundIndexLoader.cpp",
    "index/BackgroundIndexStorage.cpp",
    "index/BackgroundQueue.cpp",
    "index/BackgroundRebuild.cpp",
    "index/CanonicalIncludes.cpp",
    "index/FileIndex.cpp",
    "index/Index.cpp",
    "index/IndexAction.cpp",
    "index/MemIndex.cpp",
    "index/Merge.cpp",
    "index/ProjectAware.cpp",
    "index/Ref.cpp",
    "index/Relation.cpp",
    "index/Serialization.cpp",
    "index/StdLib.cpp",
    "index/Symbol.cpp",
    "index/SymbolCollector.cpp",
    "index/SymbolID.cpp",
    "index/SymbolLocation.cpp",
    "index/SymbolOrigin.cpp",
    "index/YAMLSerialization.cpp",

    "index/dex/Dex.cpp",
    "index/dex/Iterator.cpp",
    "index/dex/PostingList.cpp",
    "index/dex/Trigram.cpp",

    "refactor/InsertionPoint.cpp",
    "refactor/Rename.cpp",
    "refactor/Tweak.cpp",
};

pub const llvm_tablegen_common_lib_cpp_files = &.{
    "GlobalISel/CodeExpander.cpp",
    "GlobalISel/CombinerUtils.cpp",
    "GlobalISel/CXXPredicates.cpp",
    "GlobalISel/GlobalISelMatchTable.cpp",
    "GlobalISel/GlobalISelMatchTableExecutorEmitter.cpp",
    "GlobalISel/PatternParser.cpp",
    "GlobalISel/Patterns.cpp",

    "AsmWriterInst.cpp",
    "CodeGenDAGPatterns.cpp",
    "CodeGenHwModes.cpp",
    "CodeGenInstAlias.cpp",
    "CodeGenInstruction.cpp",
    "CodeGenRegisters.cpp",
    "CodeGenSchedule.cpp",
    "CodeGenTarget.cpp",
    "DAGISelMatcher.cpp",
    "InfoByHwMode.cpp",
    "OptEmitter.cpp",
    "PredicateExpander.cpp",
    "SubtargetFeatureInfo.cpp",
    "Types.cpp",
    "Utils.cpp",
    "VarLenCodeEmitterGen.cpp",
};

pub const llvm_tablegen_basic_lib_cpp_files = &.{
    "ARMTargetDefEmitter.cpp",
    "Attributes.cpp",
    "CodeGenIntrinsics.cpp",
    "DirectiveEmitter.cpp",
    "IntrinsicEmitter.cpp",
    "RISCVTargetDefEmitter.cpp",
    "SDNodeProperties.cpp",
    "TableGen.cpp",
    "VTEmitter.cpp",
};

pub const llvm_min_tablegen_cpp_files = &.{
    "llvm-min-tblgen.cpp",
};

pub const llvm_tablegen_cpp_files = &.{
    "AsmMatcherEmitter.cpp",
    "AsmWriterEmitter.cpp",
    "CallingConvEmitter.cpp",
    "CodeEmitterGen.cpp",
    "CodeGenMapTable.cpp",
    "CompressInstEmitter.cpp",
    "CTagsEmitter.cpp",
    "DAGISelEmitter.cpp",
    "DAGISelMatcherEmitter.cpp",
    "DAGISelMatcherGen.cpp",
    "DAGISelMatcherOpt.cpp",
    "DecoderEmitter.cpp",
    "DFAEmitter.cpp",
    "DFAPacketizerEmitter.cpp",
    "DisassemblerEmitter.cpp",
    "DXILEmitter.cpp",
    "ExegesisEmitter.cpp",
    "FastISelEmitter.cpp",
    "GlobalISelCombinerEmitter.cpp",
    "GlobalISelEmitter.cpp",
    "InstrDocsEmitter.cpp",
    "InstrInfoEmitter.cpp",
    "llvm-tblgen.cpp",
    "MacroFusionPredicatorEmitter.cpp",
    "OptionParserEmitter.cpp",
    "OptionRSTEmitter.cpp",
    "PseudoLoweringEmitter.cpp",
    "RegisterBankEmitter.cpp",
    "RegisterInfoEmitter.cpp",
    "SDNodeInfoEmitter.cpp",
    "SearchableTableEmitter.cpp",
    "SubtargetEmitter.cpp",
    "WebAssemblyDisassemblerEmitter.cpp",
    "X86InstrMappingEmitter.cpp",
    "X86DisassemblerTables.cpp",
    "X86FoldTablesEmitter.cpp",
    "X86MnemonicTables.cpp",
    "X86ModRMFilters.cpp",
    "X86RecognizableInstr.cpp",
};

pub const llvm_tablegen_lib_cpp_files = &.{
    "DetailedRecordsBackend.cpp",
    "Error.cpp",
    "JSONBackend.cpp",
    "Main.cpp",
    "Parser.cpp",
    "Record.cpp",
    "SetTheory.cpp",
    "StringMatcher.cpp",
    "TableGenBackend.cpp",
    "TableGenBackendSkeleton.cpp",
    "TGLexer.cpp",
    "TGParser.cpp",
    "TGTimer.cpp",
};

pub const lldb_tablegen_cpp_files = &.{
    "LLDBOptionDefEmitter.cpp",
    "LLDBPropertyDefEmitter.cpp",
    "LLDBTableGen.cpp",
    "LLDBTableGenUtils.cpp",
};

pub const clang_tablegen_cpp_files = &.{
    "ASTTableGen.cpp",
    "ClangASTNodesEmitter.cpp",
    "ClangASTPropertiesEmitter.cpp",
    "ClangAttrEmitter.cpp",
    "ClangBuiltinsEmitter.cpp",
    "ClangCommentCommandInfoEmitter.cpp",
    "ClangCommentHTMLNamedCharacterReferenceEmitter.cpp",
    "ClangCommentHTMLTagsEmitter.cpp",
    "ClangDataCollectorsEmitter.cpp",
    "ClangDiagnosticsEmitter.cpp",
    "ClangOpcodesEmitter.cpp",
    "ClangOpenCLBuiltinEmitter.cpp",
    "ClangOptionDocEmitter.cpp",
    "ClangSACheckersEmitter.cpp",
    "ClangSyntaxEmitter.cpp",
    "ClangTypeNodesEmitter.cpp",
    "MveEmitter.cpp",
    "NeonEmitter.cpp",
    "RISCVVEmitter.cpp",
    "SveEmitter.cpp",
    "TableGen.cpp",
};

pub const clang_support_lib_cpp_files = &.{
    "RISCVVIntrinsicUtils.cpp",
};

pub const demangle_cpp_files = &.{
    "Demangle.cpp",
    "ItaniumDemangle.cpp",
    "MicrosoftDemangle.cpp",
    "MicrosoftDemangleNodes.cpp",
    "RustDemangle.cpp",
    "DLangDemangle.cpp",
};
